//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysoap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public string ProductImageUrl { get; set; }
        public int Stock { get; set; }
        public string MPUrl { get; set; }
        public int Stars { get; set; }
        public string MPRefCode { get; set; }
        public int DeliveryDate { get; set; }
    }
}
